### ISSUE TITLE
Problems with utf-8 encoding

### ISSUE THREAD

**Issue by anothergituser** [jeroendesloovere/vcard#115]
Can not download vcard when having characters like ñ or á in firstname or lastname and usign utf-8 encoding. Output works.
Changing encoding in VCard class from utf-8 to iso-8859-1 seems to work for downloads too but i noticed that the encoding is not specified in the vcf file.
Thanks

**Comment by lanzaldo** [comment]
Same problem!

**Comment by christianruhstaller** [comment]
See: https://github.com/jeroendesloovere/vcard/pull/119

**Comment by jeroendesloovere** [comment]
Can you confirm the release 1.6 fixed this?
