### ISSUE TITLE
Gender in vCard

### ISSUE THREAD

**Issue by lanzaldo** [jeroendesloovere/vcard#118]
Hi,

is there a possibility to add the gender to the vcard object?

**Comment by jeroendesloovere** [comment]
Hi @lanzaldo,

In the current master version that is not possible.
You can always create a Pull Request for this feature.

> We are working towards a completely new version, which supports Gender.
You can find the Work in Progress code over here: https://github.com/jeroendesloovere/vcard/tree/new-version
