### ISSUE TITLE
windows contacts compatibility

### ISSUE THREAD

**Issue by Spica2** [jeroendesloovere/vcard#120]
Is maybe related to #115 and #119

Downloads on windows machines result with wrong special characters e.g. ä ü ö in windows contacts. In a text editor the file looks good. So I am not shure if windows is not vcard 3.0 aligned or if there is a formatting problem. Fix mentioned in #119 does not help.

**Comment by Spica2** [comment]
The only way in my testenvironment that suceeded was to encode a vcard in charset=ISO-8859-1, set the mime type to charset=ISO-8859-1, and put charset=ISO-8859-1 in each line where special characters where used. The cards were read in windows, mac and android correctly.

**Comment by jeroendesloovere** [comment]
Can you confirm the release 1.6 fixed this?
