### ISSUE TITLE
Parse vcrad from qrcode

### ISSUE THREAD

**Issue by anoopzoondia** [jeroendesloovere/vcard#121]
Storing the QR code in a vcard format. Is there any option in this module to parse the vcard that is embed in a QR code that is saved in a png or jpeg format? Or the string vcard can we process using this library?

**Comment by jeroendesloovere** [comment]
You can parse the vCard string from the QR Code.
https://github.com/jeroendesloovere/vcard#parsing-examples

**Comment by anoopzoondia** [comment]
But i can see only the option to parse from the .vcf file only, not from the image files like .png or .jpeg. Can i just rename the .vcf  extension to that .png or .jpeg

**Comment by jeroendesloovere** [comment]
Handling QR codes is not something `jeroendesloovere/vcard` library handles.
You need another library to read the "text" from the QR-image.
With that "text" (= string) you can probably parse it to a vCard.

**Comment by anoopzoondia** [comment]
Yes got it clear.

**Comment by anoopzoondia** [comment]
Will this plugin work in php 7? When i run composer command i got like this

![image](https://user-images.githubusercontent.com/3204788/37293929-b29f5734-263a-11e8-8b4b-5fc1471b55cb.png)

**Comment by jeroendesloovere** [comment]
Can you try `composer install jeroendesloovere/vcard:^1.6` ?

**Comment by anoopzoondia** [comment]
This is also not working for me

**Comment by jeroendesloovere** [comment]
Sorry, typo, should be: `composer require jeroendesloovere/vcard:^1.6`

**Comment by anoopzoondia** [comment]
![image](https://user-images.githubusercontent.com/3204788/37354818-86ec88ea-2708-11e8-8fc4-1f497cb00cb1.png)
Again same issue.

**Comment by jeroendesloovere** [comment]
Can you remove the `vendor` folder and the composer.lock file?
Then execute the command again.
Are you using the `vcard-bundle`?

**Comment by anoopzoondia** [comment]
No
