### ISSUE TITLE
Single card containing all contacts rather than individual cards

### ISSUE THREAD

**Issue by interludic** [jeroendesloovere/vcard#125]
I would like to import into google contacts, however they require single file import.

Google contacts will accept 1 file with multiple cards inside.

Would this be easy to do?

**Comment by jeroendesloovere** [comment]
I guess this is currently possible

**Comment by jeroendesloovere** [comment]
Herefore I reference to https://github.com/jeroendesloovere/vcard/pull/101

**Comment by polcape** [comment]
Hi, does this feature is present now in the master branch?

Thanks
