### ISSUE TITLE
SSL operation failed with code 1.

### ISSUE THREAD

**Issue by Tarasovych** [jeroendesloovere/vcard#132]
I got an error while trying to download VCard. I'm using this library with Laravel framework. Laravel is served locally over https.

Error:

> get_headers(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

Fails on [this](https://github.com/jeroendesloovere/vcard/blob/master/src/VCard.php#L234) line.

**Comment by jeroendesloovere** [comment]
Hit @Tarasovych, thanks for contacting us.

I searched Google and it seems to be an error in your local setup.
Can you try the following solutions: https://github.com/composer/composer/issues/3346#issuecomment-76593763

**Comment by Tarasovych** [comment]
@jeroendesloovere thanks, but that sollution is suitable for Linux, as I can see (I use OpenServer for Windows).
