### ISSUE TITLE
Returned data is not an image.

### ISSUE THREAD

**Issue by Tarasovych** [jeroendesloovere/vcard#133]
I have two Laravel apps. Both on the same commit state.

First app domain is like `foo.bar.example.com`, second is `bar.example.com`. Both served via same web-server and have ssl certificate (if that matters for my issue).

Both apps store images in the same folder, folder has 0755 permission and the same user is an owner.

I have such code:
```php
$this->vcard->addPhoto($this->screenshot);
```
and it cause some problems.

This:
```php
var_dump($this->screenshot);
```
returns valid link to an image - I've checked on both sites.

So I can say that `addPhoto()` always get valid string as an argument.

BUT being on `foo.bar.example.com` I got `Returned data is not an image.`. What can be a problem? Thank you!

P. S. I've also tried `addPhoto('https://foo.bar.example.com/path/to/image/file.jpg')` - same error.

P.P.S This works somehow: `addPhoto('https://bar.example.com/path/to/image/file.jpg')`, `addPhoto(public_path('path/to/image/file.jpg'))`. Can't understand. Both urls return identical headers when executed in browser.

**Comment by Tarasovych** [comment]
I've solved my issue: using relative path instead absolute. But I want to investigate this problem more - why absolute path causes an error?

**Comment by nam-co** [comment]
Hi @Tarasovych were you able to find a solution? I face the same issue, some url works and others don't (I use DO spaces), appreciate any guidance

**Comment by Tarasovych** [comment]
@nam-co nope(

**Comment by nam-co** [comment]
@Tarasovych is there an option to turn the image format verification off?

**Comment by nam-co** [comment]
I just got the same error with a simple png: 
![](https://s3.showpage.app/showpage/biz/39/pages/99/dario-qpau5.png)

**Comment by Tarasovych** [comment]
I don't use the library for long, so I can't help
