### ISSUE TITLE
Fatal error: Call to undefined function JeroenDesloovere\VCard\finfo_open() 

### ISSUE THREAD

**Issue by szmulik** [jeroendesloovere/vcard#15]
Hello
I'm getting error when I try to run example
Fatal error: Call to undefined function JeroenDesloovere\VCard\finfo_open() in /....../vcard/src/VCard.php on line 125

I use php 5.3

**Comment by jeroendesloovere** [comment]
Hi there,
you can temporarily use [previous version](https://github.com/jeroendesloovere/vcard/releases/tag/1.1.4) while I check for a solution.

**Comment by szmulik** [comment]
Thanks jeroendesloovere
