### ISSUE TITLE
Issue using iphone

### ISSUE THREAD

**Issue by luizamanhaes1** [jeroendesloovere/vcard#159]
I'm facing an issue when trying to import the generated vcard on iphone. Before the iOS 13 update, when the vcard opened, the user could click on "Open in contacts", but now this option doesn't even appear or appear very hidden as "Copy to Contacts" but it seens like a disabled button.

Does anyone how to overcome this?

**Comment by l3dlp** [comment]
Hello. As far as I investigate this issue, I found that it still be possible, but not fluid anymore.

When you click and download the .vcf file, a preview of the Contact appears. Click 1 second on the picture to get the new menu on screen, with fully functional "add to contact" and "update contact" links.

**Comment by luizamanhaes1** [comment]
It worked! Didn't know about this function hehe thank you so much!
