### ISSUE TITLE
Any plans to add parsing?

### ISSUE THREAD

**Issue by wadmiraal** [jeroendesloovere/vcard#17]
To turn this into a complete package, do you have any ideas to add Vcard parsing to your library?

**Comment by jeroendesloovere** [comment]
Hi @wadmiraal,
Thanks for reporting your issue.
Is it possible to be a bit more specific about what output you want?

If you mean you want to get the string?
Then you can use the functions buildVCard() or buildVCalendar().

**Comment by wadmiraal** [comment]
No, I mean the opposite :). Getting a Vcard string and parse its fields,
transforming it to an object (or array of objects).

That would make your library the one-stop-shop for everything Vcard in PHP
Le 20 févr. 2015 15:33, "Jeroen Desloovere" <notifications@github.com> a
écrit :

**Comment by jeroendesloovere** [comment]
Hi @wadmiraal,
Seems like a nice feature to add.
I will take a closer look if this could be possible,
since I want it to work across different vCard versions.

**Comment by wadmiraal** [comment]
I can have a look at it. It will give me the opportunity to dig a bit more into this format.

Read your contribution guidelines: that's the kind of stuff that makes me want to contribute :-). Especially the Unit Test part (I won't event consider using a library that has no tests nowadays).

**Comment by jeroendesloovere** [comment]
@wadmiraal Ok, feel free to add a Pull Request for your implementation.

**Comment by three3211** [comment]
+1 this. This would be really useful!

**Comment by jeroendesloovere** [comment]
Hi @wadmiraal, any news about this?

**Comment by wadmiraal** [comment]
The project I'm working on got a bit delayed, but this feature will
definitely be needed. I'm already leveraging your library for the export
part (which works really well), and will start working on the import in the
coming weeks. When done, I will definitely submit a PR.

**Comment by wadmiraal** [comment]
[PR here.](https://github.com/jeroendesloovere/vcard/pull/63)
