### ISSUE TITLE
Workaround for iOS devices is no longer needed for the latest iOS version.

### ISSUE THREAD

**Issue by jeroendesloovere** [jeroendesloovere/vcard#18]
## > iOS 8
I have discovered that iOS 8 now supports .vcf files.
> So we need to reprogram the isIOS() function.

## For previous versions of < iOS 8 we did a workaround
iOS had no support for .vcf (vcard) files. So I build a workaround that uses .icf (vcalender).

**Comment by stadskle** [comment]
What is the status of this? I am testing with 1.18 now, and it does not seem to be fixed.
