### ISSUE TITLE
Deprecated: Required parameter $element follows optional parameter $include in ....vendor/jeroendesloovere/vcard/src/VCard.php on line 228

### ISSUE THREAD

**Issue by nabeelalihashmi** [jeroendesloovere/vcard#181]
I get this issue.

Fix:  
File: vendor/jeroendesloovere/vcard/src/VCard.php | line 228:    private function addMedia($property, $url, $element,$include = true)
vendor/jeroendesloovere/vcard/src/VCard.php | lines 432-442:  public function addLogo($url, $include = true)
    {
        $this->addMedia(
            'LOGO',
            $url,
            'logo',
            $include
        );

        return $this;
    }

**Comment by iamkbkarthikeyan** [comment]
Hi, @nabeelalihashmi  Same Happend on my PHP 8.

**Comment by nadeem706** [comment]
@iamkbkarthikeyan same happend to me on php8. You have any alternate solution for it?

**Comment by tringalama2** [comment]
same issue.  it is a compatibility issue with PHP 8.0.  

I made the fix, updated composer.json to PHP 8 and PHPUnit to 9.3 and submitted a pull request.

in the meantime, you can use my fork: https://github.com/tringalama2/vcard

this is my first pull request, so any suggestions are welcome.

**Comment by jeroendesloovere** [comment]
Another MR fixes it: https://github.com/jeroendesloovere/vcard/pull/192

**Comment by jeroendesloovere** [comment]
@tringalama2 can you create a pull request to update php to 9.3?

**Comment by steccas** [comment]
This is not resolved
