### ISSUE TITLE
export many vCards in one file?

### ISSUE THREAD

**Issue by cmette** [jeroendesloovere/vcard#183]
is it possible to write many vCards in a single output stream and send them to the browser as ->download()? do you have a quick example? Greetings Christian

**Comment by Rich-e-js** [comment]
im also interested on this. i just simpli tried to add another name and number but i got an 'You can only set "name" once' error.

**Comment by neuhaus** [comment]
This issue appears to be a direct duplicate of issue #170

**Comment by jeroendesloovere** [comment]
vcard v2.0.0 will be able to handle this
