### ISSUE TITLE
addLabel() doesn't add $this->getCharsetString()

### ISSUE THREAD

**Issue by lerni** [jeroendesloovere/vcard#188]
Is there a particular reason why encoding isn't added to LABEL? On Windows this causes Problems with Umlauts.

**Comment by jeroendesloovere** [comment]
Hi there, nice catch.
I just added it for you.

**Comment by jeroendesloovere** [comment]
New release https://github.com/jeroendesloovere/vcard/releases/tag/1.7.3

**Comment by lerni** [comment]
:heart: Thank you!
