### ISSUE TITLE
New release for PHP 8.0?

### ISSUE THREAD

**Issue by LordSimal** [jeroendesloovere/vcard#197]
since the PHP 8.0 issues have been resolved can we please do a new release tagging the latest version so we can properly download it via composer?

**Comment by noelkalel** [comment]
any news about this feature?

**Comment by MasterZydra** [comment]
Any update on this?

**Comment by chedri** [comment]
Hi. Would be good to know when the release will take place. Thanks

**Comment by LordSimal** [comment]
well, this repo is pretty dead so good luck anyone using this.
Fortunately I was able to remove the vcard feature in my app so I don't need this anymore
