### ISSUE TITLE
New tag for master

### ISSUE THREAD

**Issue by beattie19** [jeroendesloovere/vcard#215]
Hey, we are currently using this package and getting the following warnings showing in our console and error tracking tool:

`1x: Optional parameter $include declared before required parameter $element is implicitly treated as a required parameter`

I was thinking to make the relevant change and create a pull request but I've noticed that this has actually already been fixed [here](https://github.com/jeroendesloovere/vcard/commit/e2848e179cc6e7ea3d0bdf4af805cd351e583c26) and I think all that is needed is for a new tag to created then we should be able to pick up these changes.

I'm happy to assist if there is anything I can do push this along

**Comment by jeroendesloovere** [comment]
Done

[Version 1.7.4 is released](https://github.com/jeroendesloovere/vcard/releases/tag/v1.7.4)

**Comment by beattie19** [comment]
Thanks @jeroendesloovere, really appreciate it and for the quick turnaround 🎉
