### ISSUE TITLE
Remove get() function

### ISSUE THREAD

**Issue by jeroendesloovere** [jeroendesloovere/vcard#22]
This function should be deprecated in favor of the function ->getOutput(), which more describes what it actually does.

**Comment by SmokeyBrandie** [comment]
The function get() does not work at the moment since it does not return anything:

    public function get()
    {
        $this->getOutput();
    }

**Comment by jeroendesloovere** [comment]
Hi @SmokeyBrandie, I'm closing this issue because I already fixed this :+1:
