### ISSUE TITLE
MIME types need updating?

### ISSUE THREAD

**Issue by Synchro** [jeroendesloovere/vcard#28]
The official MIME type for VCards/vcf is apparently `text/vcard`, and the type for iCalendar/ics files is meant to be `text/calendar` according to [RFC6350](http://tools.ietf.org/html/rfc6350#section-10.1) and [RFC5545](http://tools.ietf.org/html/rfc5545). This VCard class instead sets the types to `text/x-vcard` and `text/x-vcalendar` respectively in the `getContentType` method. Is there any reason not to update to those?

**Comment by jeroendesloovere** [comment]
Hi @Synchro,
using the '''text/v-card''' and '''text/x-vcalender''' supports older vcard versions while your suggestion only support > v3.

But will look into this in the future when I [refactor buildVcalender out](https://github.com/jeroendesloovere/vcard/issues/18).
