### ISSUE TITLE
Ability to Add Multiple Addresses, Dates and Emails

### ISSUE THREAD

**Issue by three3211** [jeroendesloovere/vcard#30]
I currently do not see a way of adding multiple addresses, dates, or emails to a vCard. You can do this with the addPhoneNumber() function, but the other functions do not seem to support this. Here is an example:

```php
    $queryEmails  = "SELECT * FROM contact_emails WHERE contact_id = $contactID";
    $resultEmails  = mysqli_query($dbc, $queryEmails);
    $numEmails    = mysqli_num_rows($resultEmails);

	if ($numEmails >= 1) {
		// There are emails associated with this contact
		while ($email = mysqli_fetch_array($resultEmails, MYSQLI_ASSOC)) {
			$vcard->addEmail($email['email'], $email['label']);
		}
	}
```

Lets say the example contact above has 3 email addresses on file. When doing the while loop, only the last email in the loop is stored in the vCard. The first 2 emails are overridden.

So is it possible for you to update this?

**Comment by jeroendesloovere** [comment]
@three3211 This is definitely something that should be integrated.
Will look into this when I add the possibility to add multiple vCards into one file.
Thanks for posting!

**Comment by three3211** [comment]
@jeroendesloovere Awesome thanks for the enhancement!

**Comment by jeroendesloovere** [comment]
Hi @three3211.
This functionality is integrated since [1.2.0](https://github.com/jeroendesloovere/vcard/releases/tag/1.2.0)
