### ISSUE TITLE
Why is JeroenDesloovere\VCard\VCard::addMedia() private?

### ISSUE THREAD

**Issue by tristanleboss** [jeroendesloovere/vcard#40]
Hello,

I am wondering why JeroenDesloovere\VCard\VCard::addMedia() is private? Indeed, because of this, it's impossible to add a logo.

There is a addPhoto method but no addLogo method. Unfortunately, calling addMedia('LOGO', URL) directly will throw an error.

Regards,

Tristan

**Comment by jeroendesloovere** [comment]
Hi @tristanleboss,
You can use -> addPhoto() which has the same result.

**Comment by tristanleboss** [comment]
addMedia allows to specify the type LOGO or PHOTO as its first parameter. addPhoto doesn't allow this, it only accepts the filename and calls addMedia with PHOTO as type.

**Comment by jeroendesloovere** [comment]
Yes I know, I remember that the VCard class once had the addLogo() function. But I removed it, because loading in a vcard on the computer, only one image was used.
If you like, I can still add that function again, @tristanleboss ?

**Comment by jeroendesloovere** [comment]
@tristanleboss bump
