### ISSUE TITLE
newline symbol at end of mime-type

### ISSUE THREAD

**Issue by verevskoy** [jeroendesloovere/vcard#41]
https://github.com/jeroendesloovere/vcard/blob/75508baac804fb0995e0df94b306d4f1c72def53/src/VCard.php#L163

Why **"\n"** at the end?

**Comment by jeroendesloovere** [comment]
@verevskoy I've got no idea. Thanks for mentioning!
That must have come in by a PR.

I've removed it in the "master" branch.
