### ISSUE TITLE
AJAX 

### ISSUE THREAD

**Issue by netidan** [jeroendesloovere/vcard#42]
im trying to use your plugin with ajax request, and i need to download the file at the end.
the vcard is being created but not downloaded, can u please help?
thanks
website: http://bestcard.shakuf.tk/?page_id=2

**Comment by mgrundkoetter** [comment]
Can you please post some code? Maybe in a Gist?!

**Comment by jeroendesloovere** [comment]
Hi @netidan,

Thanks for your question.
I guess you where using ```$vcard->->download()```? If so, you have to change that way of working. There are a lot of solutions.

Example:
* Saving the vcard to a file
* Pushen the URL to that file in your AJAX response.
* Let Javascript open a new window to that vcard

**Comment by netidan** [comment]
hi, 
yes you are right im using $vcard->download()
i changed the ajax to simple form and now its working. 
thanks.

**Comment by jeroendesloovere** [comment]
@netidan Glad I could help you.

**Comment by jeroendesloovere** [comment]
Thanks to @mgrundkoetter for helping to maintain the issues :+1:

**Comment by netidan** [comment]
hi i have another problem.
i need to save the vcard file with ansi (WINDOWS-1255) encoding.
i tried to change public $charset to windows-1255 but it didnt work (the file i download is encoded in utf8 without bom)
i managed to fix it on Chrome by adding accept-charset="windows-1255" attr to the form but it doesnt work on ie. 
any suggestions?
thanks
