### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by netidan** [jeroendesloovere/vcard#44]
hi i have another problem.
i need to save the vcard file with ansi (WINDOWS-1255) encoding.
i tried to change public $charset to windows-1255 but it didnt work (the file i download is encoded in utf8 without bom)
i managed to fix it on Chrome by adding accept-charset="windows-1255" attr to the form but it doesnt work on ie. 
any suggestions?
thanks

**Comment by netidan** [comment]
(sorry for double posting the other thread was closed)

**Comment by netidan** [comment]
fixed by adding some js
document.charset = 'WINDOWS-1255';

**Comment by jeroendesloovere** [comment]
@netidan Thanks for mentioning your fix!
