### ISSUE TITLE
Vcard Encoding

### ISSUE THREAD

**Issue by dvlppr** [jeroendesloovere/vcard#45]
How can I add  latin1 (iso8859-1) support ? 
i have `ChargÃ©(e)` instead of `Chargé(e)`

**Comment by jeroendesloovere** [comment]
Hi, would it help you if there was a ->setCharset($charset) method?

**Comment by dvlppr** [comment]
What I have to do to have the correct encoding is (from your example)
``` php 
<?php
$vcard = new VCard();
$lastname = utf8_decode($user->prenom);
$firstname = utf8_decode($user->nom);
$additional = '';
$prefix = '';
$suffix = '';

// add personal data
$vcard->addName($lastname, $firstname, $additional, $prefix, $suffix);

```

**Comment by jeroendesloovere** [comment]
The default encoding works fine for me. But I've added the setCharset() and getCharset() functions so everyone can do what he likes. Check the [latest release 1.2.1](https://github.com/jeroendesloovere/vcard/releases/tag/1.2.1) for these functions.
