### ISSUE TITLE
Problem with Persian characters

### ISSUE THREAD

**Issue by jeroendesloovere** [jeroendesloovere/vcard#48]
**Problem**

As described by @sajjadrad, building a vCard with some Unicode characters (for example in persian : سجاد راد ) isn't creating the right words (false => ط¨ط§ط²غŒع¯ط±). And when importing in Microsoft Outlook, it is wrong.

Check #47 for more information

**Comment by jeroendesloovere** [comment]
Anybody has a solution for this?

**Comment by giorgiopagnoni** [comment]
Same with accented letters (e.g. à è ò é), that come up as ? on Android.

**Comment by jeroendesloovere** [comment]
@giorgiopagnoni Can you tell me which version you are using?

**Comment by giorgiopagnoni** [comment]
1.2.2. Should I switch to another one?

**Comment by giorgiopagnoni** [comment]
It seems to be working if I utf8_encode my fields.

**Comment by sajjadrad** [comment]
I added utf8 encoding to all tags in my last commit but as you said It's not standard.I found another bug in IOS contact.
![image](https://cloud.githubusercontent.com/assets/1608837/14075769/3f8cb830-f4f1-11e5-839d-4aec5a833a63.jpeg)

**Comment by jeroendesloovere** [comment]
@sajjadrad You should use the class and not adding utf8 encoding.
Everything works fine in iOS.

**Comment by sajjadrad** [comment]
@jeroendesloovere check this out: 
https://atbox.io/sajjad/vcard

Persian characters problem exists in MS outlook,ios and android contact.

**Comment by jeroendesloovere** [comment]
Thanks @sajjadrad 
Can you copy/paste the exact PHP code that you used over here? Thanks
![schermafbeelding 2016-04-15 om 10 48 10](https://cloud.githubusercontent.com/assets/588616/14556256/8f74a2ae-02f7-11e6-92a5-eed266f56bc5.png)

**Comment by sajjadrad** [comment]
@jeroendesloovere  I found the problem. while converting with utf8_decode function, unicode characters converted to question mark (?) as wrong. You used this function for show it properly in MS outlook. I commented it and used exported vcard in android and ios, problem solved but the old problem (outlook) exists while utf8_decode function doesn't use.

**Comment by sajjadrad** [comment]
I checked output with utf8_decode function in MS outlook. like andorid and ios all persian characters replaced with question marks.

**Comment by jeroendesloovere** [comment]
Don't really know what you mean and what I have to do?

**Comment by sajjadrad** [comment]
I think outlook problem is from it's charset config. I couldn't find any charset settings. The file encoding is right but outlook open it without utf-8 encoding.

**Comment by sajjadrad** [comment]
Outlook is opening file with Arabic(windows-1256) encoding. It's wrong.

**Comment by sajjadrad** [comment]
This is the problem:

http://stackoverflow.com/questions/8617439/utf8-encoding-with-vcards-in-windows

Also, please remove this code for correct encoding in ios and android:
https://github.com/jeroendesloovere/vcard/blob/master/src/VCard.php#L580

**Comment by sajjadrad** [comment]
This bug fixed is pull request #51 but it has not any tags. Composer updates v1.1.2 while pull request has been merged with dev master.

**Comment by sajjadrad** [comment]
Just utf8_decode function must removed, because each line has charset attribute and there is no need to this function for converting.
