### ISSUE TITLE
PHP Fatal error:  Class 'JeroenDesloovere\VCard\VCard' not found in /srv/www/autofill.dabase.com/vcf/index.php on line 6

### ISSUE THREAD

**Issue by kaihendry** [jeroendesloovere/vcard#49]
<img src=http://s.natalian.org/2015-09-25/1443172951_1912x1036.png>

What am I missing?

**Comment by kaihendry** [comment]
After reading https://jtreminio.com/2012/10/composer-namespaces-in-5-minutes/ and f!cking around for 10 minutes I discovered:


    require_once __DIR__.'/vendor/autoload.php';
    require_once __DIR__ . '/vendor/jeroendesloovere/vcard/src/VCard.php';
    use JeroenDesloovere\VCard\VCard;


Not entirely sure why it's so hard. :(

**Comment by tc0nn** [comment]
This didn't work for me. And I'm also confused as to why this is so hard. Here's what I ended up with:
First run composer without complaints, then dev-master, then add the requires:
```
composer update --with-dependencies
composer require jeroendesloovere/vcard dev-master
```
Top of my file looks like:
```
require'vendor/autoload.php';
require 'src/VCard.php';
use JeroenDesloovere\VCard\VCard;

```

Good luck.
