### ISSUE TITLE
addName

### ISSUE THREAD

**Issue by kaihendry** [jeroendesloovere/vcard#50]
I want to be able just supply a name http://autofill.dabase.com/ in free form. And that would just become:

     FN;CHARSET=UTF-8:John Doe

Could your API be simpler, please?

**Comment by jeroendesloovere** [comment]
Hi @kaihendry, that is bad practice.
FirstName and LastName must be separated.

**Comment by jeroendesloovere** [comment]
But I understand why you want such functionality.
I'll think about it.

**Comment by JoeThielen** [comment]
I would like to second this request.  Although I personally completely agree that the name should be separated as much as possible, sometimes we're faced with situations where we're not in complete control of the data we receive or have to work with.

**Comment by jeroendesloovere** [comment]
Hi @kaihendry, you can just do the following:
```php
->addName('John Doe');
```
