### ISSUE TITLE
Not Working with UTF-8 and Outlook 2010 Windows 8 Machine

### ISSUE THREAD

**Issue by gizzm0** [jeroendesloovere/vcard#53]
Hi Jero,

nice small project y worte, ty for that!

I foudn after 3 hours now, that for working in outlook we need to "utf8_decode" the output to show right chars in outlook 2010. I know that this is a f..ing s..t bug from outlook but i need to support it. So i either have to copy your code and adapt it, or you/me could integrate this into the VCard class. It is quite simple.  

   public function getOutput()
    {
       $output = ($this->isIOS7()) ?
            $this->buildVCalendar() : $this->buildVCard();
       if ($this->getCharset() == 'utf-8') {
         $output = utf8_decode($output);
      }

        return $output;
    }

But i did not tested it on other webcielnst thats my problem...

best regards gizzmo

**Comment by jeroendesloovere** [comment]
Hi @gizzm0? Outlook truly sucks.
But indeed, as a dev you need to support that piece of crap to.
I'll look into this.

**Comment by jeroendesloovere** [comment]
Updated the master with https://github.com/jeroendesloovere/vcard/commit/af7401396156d15513bbf73e12c5b7a839413ca5

**Comment by jeroendesloovere** [comment]
Can you confirm that this [release](https://github.com/jeroendesloovere/vcard/releases/tag/1.2.2) fixes the problem?

**Comment by gizzm0** [comment]
Hi Jero,

thank you for the fast reply and fix, thats really great!

Yes i can confirm that this fixes my problem with Outlook 2010 and additionaly i testes it with www.gmx.de ( a german email provider with webinterface) and it works too:-)

Best regards gizzmo

**Comment by jeroendesloovere** [comment]
Thanks @gizzm0 for your quick answer.
Glad it solved your problem.

**Comment by maxinuss** [comment]
Guys, this change cause charset codification problems in Thunderbird. You should remove this fix and change this line in buildVCard() methond to fix it in Outlook:

$string .= $this->fold($property['key'] . ':' . $property['value'] . "\r\n");

replace with:

$string .= $this->fold($property['key'] . ';charset=utf-8:' . $property['value'] . "\r\n");

**Comment by gizzm0** [comment]
@jeroendesloovere @maxinuss is right my fix does not work in Thunderbird, but the fix from maxinuss works, i tested it for Outlook 2010 Win8 and Thunderbird 38.5.1 Win8
