### ISSUE TITLE
please help - cant download in native android browser

### ISSUE THREAD

**Issue by netidan** [jeroendesloovere/vcard#56]
hi jeroen,
im still having problems saving vcf files in native android browser, apparently the problem is not related to lg phones as i thought.
i found out that if i remove the image i can download the file.
you previously marked my issue as invalid, i beg you to take another look before you decide to do so again.
many thanks

**Comment by jeroendesloovere** [comment]
Hi @netidan,
hmmm sorry to hear that.
Its difficult for me to test this on Android, since nobody in my environment has an Android.
Everybody has switched to iOS.
Anybody to the rescue here?

**Comment by jeroendesloovere** [comment]
Closed since duplicate issue for #56
