### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by audas** [jeroendesloovere/vcard#57]
Hi - images are being encoded and appear when in phone, however not in outlook or Microsoft Address book, nor Thunderbird.

And ideas on this ?

**Comment by jeroendesloovere** [comment]
Hmmm, maby just buying a decent OS will do the trick. I could recommend Mac OS X

**Comment by audas** [comment]
Ummm. Not due to the operating system. Doesn't work.

**Comment by jeroendesloovere** [comment]
@audas Everything works perfectly on Mac OS X, so this is definitely a Windows OS flaw (as always).
Can you give us
- the exact version of your OS?
- the exact version of your mail program?

So I can take a look.
Thanks

**Comment by audas** [comment]
Actually its not going to be a windows OS flaw because every other library works with images in calendar images. If it was an OS flaw, none of them would work. Hence its  a flaw in your code - pure and simple.

Does not work on ANY windows devices from 7 - 10 on any clients. Basically it only works on iPhone.

Does not even work in Chrome.

**Comment by jeroendesloovere** [comment]
Hi @audas,
I'm coming back to your image problem.
There are already some releases since you had that problem.
Could it be possible to test again and notify me if it works or not?

Would be nice.

**Comment by jeroendesloovere** [comment]
I've closed this for now.
