### ISSUE TITLE
getOutput() "destroys" UTF-8

### ISSUE THREAD

**Issue by HostedDinner** [jeroendesloovere/vcard#59]
If the output is suppose to be UTF-8 ($this->getCharset() == 'utf-8') then it is a bad idea to use the function utf8_decode to convert most exotic characters back to ISO-8859-1...
This will always lead to missing UTF-8 characters in the output.

**Comment by jeroendesloovere** [comment]
I'm going to close this one as I assume the vCard does not use utf8_decode anymore.
Feel free to provide a fixing PR if you find this somewhere as a bug...
