### ISSUE TITLE
Submit URL for image

### ISSUE THREAD

**Issue by rkorebrits** [jeroendesloovere/vcard#60]
Why is there only and option to specify and image via a local path, why can we not just provide a URL?

Otherwise really like the tool! Thanks!

**Comment by jeroendesloovere** [comment]
Hi @rkorebrits.
Don't know, didn't really tested this with external image.
I guess when using external url, the $include should be true then?

**Comment by rkorebrits** [comment]
Looks like `$include` should be `false`, however the format that comes out is incorrect, according to https://en.wikipedia.org/wiki/VCard#vCard_3.0 and I've tested it and it doesn't work. 

The output when false is: `PHOTO:http://foo/bar.png`, but according to Wikipedia should be `PHOTO;VALUE=URL;TYPE=GIF:http://www.example.com/dir_photos/my_photo.gif`

**Comment by jeroendesloovere** [comment]
Hi, thanks @rkorebrits for the information.
Don't have time to adjust this.
Can you create a PR for this?

**Comment by rkorebrits** [comment]
I amended the code to match the correct format for V3.0 and sent you a pull request

**Comment by jeroendesloovere** [comment]
Thanks @rkorebrits, I will look at it.
