### ISSUE TITLE
Version 3.0 - Mac OS X 10.11.5

### ISSUE THREAD

**Issue by aserra** [jeroendesloovere/vcard#69]
Hi @jeroendesloovere 

Parser does not recognize the previous parameter "item1" at EMAIL line and not entry into the switch cases.

I post you an example:

BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//Mac OS X 10.11.5//EN
N:;Albert;;;
FN:Albert
item1.EMAIL;type=INTERNET;type=pref:alberttest@gmail.com
item1.X-ABLabel:_$!<Other>!$_
UID:a842653d-3353-45a3-a6b9-c7fd95c1380c
X-ABUID:A842653D-3353-45A3-A6B9-C7FD95C1380C:ABPerson
END:VCARD

Thanks!

**Comment by jeroendesloovere** [comment]
Hi @wadmiraal, can you look into this?

**Comment by wadmiraal** [comment]
On it. I wasn't aware of this "group" construct (RFC mentions it, though).

**Comment by wadmiraal** [comment]
There. Unit tests included.

**Comment by wadmiraal** [comment]
PR here: #72

**Comment by jeroendesloovere** [comment]
Closing this one since the PR of @wadmiraal should have fixed it.
