### ISSUE TITLE
Multiple VCards in one file

### ISSUE THREAD

**Issue by auro1** [jeroendesloovere/vcard#7]
Any specific reason for no support for this??

**Comment by jeroendesloovere** [comment]
Hi @auro1, thanks for your issue :-D.
Well, I guess because I have never needed that functionality.

Feel free to PR such a feature :-P

**Comment by jeroendesloovere** [comment]
I reopened this issue because this function could come in handy.

**Comment by three3211** [comment]
+1 this. I have a contacts app and it would be useful to be able to allow the user to export "all contacts" instead of just one at a time.

**Comment by DieterKoblenz** [comment]
Any plans for this? Would be most useful!

**Comment by Stadly** [comment]
Isn't https://github.com/jeroendesloovere/vcard/pull/101 a PR for this feature?

**Comment by jeroendesloovere** [comment]
We are working on a new vCard version which handles this by default.
You can view the WIP over here: https://github.com/jeroendesloovere/vcard/tree/new-version
