### ISSUE TITLE
Use issues...

### ISSUE THREAD

**Issue by cedriccharles4** [jeroendesloovere/vcard#75]
Hello,

I want to use your class in a project and I'm trying to make it work, but I can't. 

Here is the content of my composer.json : 
`{
    "name": "philippepartners/law",
    "require": {
        "drewm/mailchimp-api": "^2.1",
        "jeroendesloovere/vcard": "1.2.*"
    }
}`

I have install/update composer on my project. My project is a WordPress site. The file functions.php is called on every page of the site. In that file, I have that line : 
`require_once( 'vendor/autoload.php' );`

In an other PHP file, I have this code : 
`use \JeroenDesloovere\VCard\VCard;

// define vcard
$vcard = new VCard();

// define variables
$firstname = 'Jeroen';
$lastname = 'Desloovere';
$additional = '';
$prefix = '';
$suffix = '';

// add personal data
$vcard->addName($lastname, $firstname, $additional, $prefix, $suffix);

// add work data
$vcard->addCompany('Siesqo');
$vcard->addJobtitle('Web Developer');
$vcard->addEmail('info@jeroendesloovere.be');
$vcard->addPhoneNumber(1234121212, 'PREF;WORK');
$vcard->addPhoneNumber(123456789, 'WORK');
$vcard->addAddress(null, null, 'street', 'worktown', null, 'workpostcode', 'Belgium');
$vcard->addURL('http://www.siesqo.be');

/* $vcard->addPhoto(__DIR__ . '/assets/landscape.jpeg'); */

// return vcard as a string
//return $vcard->getOutput();

// return vcard as a download
return $vcard->download();

// echo message
echo 'A personal vCard is saved in this folder: ' . __DIR__;`

When I go with my browser to that page, I have this error : 
`[27-Sep-2016 12:26:31 UTC] PHP Fatal error:  Uncaught Error: Class 'JeroenDesloovere\VCard\VCard' not found in /mysite/wp-content/themes/PhilippePartners/single-lawyer-vcard.php:15
Stack trace:
#0 /mysite/wp-includes/template.php(574): require()
#1 /mysite/wp-includes/template.php(531): load_template('/Users/cedricno...', false)
#2 /mysite/wp-includes/general-template.php(167): locate_template(Array, true, false)
#3 /mysite/wp-content/themes/PhilippePartners/single-lawyer.php(4): get_template_part('single-lawyer-v...')
#4 /mysite/wp-includes/template-loader.php(75): include('/Users/cedricno...')
#5 /mysite/wp-blog-header.php(19): require_once('/Users/cedricno...')
#6 /mysite/index.php(17): require('/Users/cedricno...')
#7 {main}
  thrown in /mysite/wp-content/themes/PhilippePartners/single-lawyer-vcard.php on line 15`

What's wrong ? Thank you in advance !

**Comment by jeroendesloovere** [comment]
Hi Cedric,
I've looked to you code, can you check if the following lines solve your problem?
`require_once __DIR__ . '/../vendor/autoload.php';`
> I've added __DIR__ 
and/or
`use JeroenDesloovere\VCard\VCard`;
> I've removed the \ before JeroenDesloovere

**Comment by cedriccharles4** [comment]
Hi Jeroen ! Thank it works :) !

I have another issue. So this totally works on my localhost. I've pushed my code to my production server and I have an error, but I don't understand why...

> Fatal error: Uncaught exception 'JeroenDesloovere\VCard\VCardMediaException' with message 'Nothing returned from URL.' in /home/clients/noomia/prod/lexing/wp-content/themes/PhilippePartners/vendor/jeroendesloovere/vcard/src/VCard.php:189 Stack trace: #0 /home/clients/noomia/prod/lexing/wp-content/themes/PhilippePartners/vendor/jeroendesloovere/vcard/src/VCard.php(343): JeroenDesloovere\VCard\VCard->addMedia('PHOTO', 'http://lexing.b...', true, 'photo') #1 /home/clients/noomia/prod/lexing/wp-content/themes/PhilippePartners/single-lawyer-vcard.php(94): JeroenDesloovere\VCard\VCard->addPhoto('http://lexing.b...') #2 /home/clients/noomia/prod/lexing/wp-includes/template.php(574): require('/home/clients/n...') #3 /home/clients/noomia/prod/lexing/wp-includes/template.php(531): load_template('/home/clients/n...', false) #4 /home/clients/noomia/prod/lexing/wp-includes/general-template.php(167): locate_template(Array, true, false) #5 /home/clients/noomia/prod/lexing/wp-content/themes/PhilippePartners/single-lawyer.php(4): get_temp in /home/clients/noomia/prod/lexing/wp-content/themes/PhilippePartners/vendor/jeroendesloovere/vcard/src/VCard.php on line 189

Thank you for your help !

**Comment by jeroendesloovere** [comment]
Hi, the error you mention is triggered on this line:
https://github.com/jeroendesloovere/vcard/blob/master/src/VCard.php#L206

Solutions:
* "file_get_contents" is not working because "allow_url_open" is probably disabled on your hosting. Can you do "phpinfo();" and check if "allow_url_open" is enabled (= ON) on your server?
* Otherwise the $url that you submit to `addMedia()` is a non existing URL?

Can you check this out?

**Comment by cedriccharles4** [comment]
Hi jeroendesloovere,

You were right, "allow_url_open" was disabled on this host ! Thank you !

**Comment by jeroendesloovere** [comment]
@cedriccharles4, I'm glad I could help you.
