### ISSUE TITLE
visit card with only email address gets no filename (edge case)

### ISSUE THREAD

**Issue by SimonHeimberg** [jeroendesloovere/vcard#76]
When I create a visit card with almost no data (only email address in my example), then filename is empty. On downloading, this resulted in a file named "vcf". (No idea where the leading . (point) was lost.)

This case could be handled in getHeaders (and maybe save and buildVCalendar). I propose a flag to getFileName. When this is set, then 'someone' is returned instead of an empty string.

This is really an edge case. But I was irritated when I got a file without any file extension.

**Comment by jeroendesloovere** [comment]
Hi, thanks for notifying.
Can you create a pull request for this and use "unknown" as filename?
Thanks in advance.
