### ISSUE TITLE
How to load in the VCard php library?

### ISSUE THREAD

**Issue by roybman** [jeroendesloovere/vcard#82]
I saw this question posted previously, and am aware the advised solution is to install composer.  However, I am running on a shared server and do not have the option of installing composer.  Downloading the files is the only way I can use this.  If there is another way I'm not aware of, I'm open to it.  Is there a set of files available for download?

**Comment by jeroendesloovere** [comment]
Well, the most easy way to do this is that you can use composer locally.
Then upload (copy/paste) the entire `vendor` folder to your shared server.
And then add the following to your PHP file where you want to use the VCard:
```php
require_once __DIR__ . '/../vendor/autoload.php';

use JeroenDesloovere\VCard\VCard;
```
Note: I would also advice to upload the composer.json and composer.lock to your server if you for any reason want to update it later...

**Comment by roybman** [comment]
Thanks for the quick response.  I haven't done this and will need to look into the particulars of how.

**Comment by jeroendesloovere** [comment]
Well, I don't know your skill level.
Here is some documentation to help you install composer:

# Composer

## Usage

### Installation

#### On MAC
``` bash
curl -sS https://getcomposer.org/installer | php
```
> It doesn't matter in which folder we are.
> If not working, try adding ``` -- --force``` at the end, which will ignore the detect_unicode setting.

Now we move it to our folder, so we can now use 'composer' as a global object.
``` bash
sudo mv composer.phar /usr/local/bin/composer
```

We should now use ```composer```

#### On Server

``` bash
curl -sS https://getcomposer.org/installer | php
```

We should now use ```php composer.phar```

### Example

We change the directory to the folder where our composer.json file is
``` bash
cd ~/Documents/My\ Tests/our-repo
```

**We have a composer.json file in our folder**

Install Composer
``` bash
composer install
```

**Comment by roybman** [comment]
Thanks.  In regards to skill level, I'm not expert, but know enough to be dangerous.  In regards to installing composer locally, I'm working on a Windows machine, but the shared server is Linux.  Would the "On Server" instructions above be run from a Windows command line, or from something like XAMPP?  Just fyi, I have been developing a new site and doing all testing right on the server, so have not yet started using XAMPP.

**Comment by jeroendesloovere** [comment]
Euhhh, Windows, don't know, all developers I know have MAC.
I think you will need to install "Putty" on Windows to be able to give in "terminal commands".

**Comment by to-be-the-best** [comment]
https://getcomposer.org/doc/00-intro.md#installation-windows

**Comment by roybman** [comment]
Thanks.  I was actually already on that page reading it.  I'm debating on taking the time now to figure this out or going ahead without Vcard on the site for now and coming back to this at a later date.
