### ISSUE TITLE
Content-length returns "0" when charset is set to other than "utf-8"

### ISSUE THREAD

**Issue by Musiksammler** [jeroendesloovere/vcard#85]
I had the problem, that I had to set the charset for vcards to "ISO-8859-1". And every data that was set into the vcard was converted using "utf8_decode".

On my development machine everything worked as expected but on the real server the downloaded vcards where just empty.

The reason is, that in "getHeaders($asAssociative)" the "strlen($this->getOutput())" call returns "0" for some reason.

**Comment by jeroendesloovere** [comment]
Closing because this will be fixed by #86
