### ISSUE TITLE
vCard is downloaded as html

### ISSUE THREAD

**Issue by turkelt0n** [jeroendesloovere/vcard#91]
On my Android-Phone (Android 4.4.2) with the standard browser, the vcard is dowloaded as a .html-file

```
vcard = new VCard();
$vcard->addCompany($companyDocument->getName());
$vcard->addEmail($companyDocument->getEmailAddress());
$vcard->addPhoneNumber($companyDocument->getPhone(), 'WORK');

return $vcard->download()
```

I did also test this on an Iphone 6 (Safari, iOS 9.3.4): It doesn't  download but instead views the vcard data directly in the browser.

Any suggestions? Thanks!

**Comment by daviddelusenet** [comment]
I'm also experiencing this issue. Have an iPhone 7 running iOS 10.3.3. @jeroendesloovere why doesn't this work?

**Comment by daviddelusenet** [comment]
@turkelt0n @jeroendesloovere I came to the conclusion that this issue has to do with the setting the wrong headers. I'm using Symfony and I used to have this setup:

```
public function downloadVcard(Application $app, $nTeamMemberId)
{
    // 1. load data
    $eTeamMember = Mimoto::service('data')->get('teamMember', $nTeamMemberId);

    // 2. generate vCard
    $vcard = VcardService::generateVcard($eTeamMember);

    // 3. download vCard
   $vcard->download();

    return false;
}
```

This setup worked on desktop computers but failed on mobile devices. Then I did some research and saw the wrong headers were being set. So I changed my code to the following:

```
public function downloadVcard(Application $app, $nTeamMemberId)
{
    // 1. load data
    $eTeamMember = Mimoto::service('data')->get('teamMember', $nTeamMemberId);

    // 2. generate vCard
    $vcard = VcardService::generateVcard($eTeamMember);

    // 3. setup filename
    $firstName = strtolower($eTeamMember->getValue('firstName'));
    $lastName = strtolower($eTeamMember->getValue('lastName'));
    $filename = str_replace(' ', '-', $firstName).'-'.str_replace(' ', '-', $lastName).'.vcf';

    // 4a. setup response
    $response = new Response();

    // 4b. add response content and status code
    $response->setContent($vcard);
    $response->setStatusCode(Response::HTTP_OK);

    // 4c. add response headers
    $response->headers->set('Content-Type', 'text/x-vcard');
    $response->headers->set('Content-Disposition', 'attachment; filename="'.$filename.'"');
    $response->headers->set('Content-Length', mb_strlen($vcard, 'utf-8'));

    // 5. return the vcard
    return $response;
}
```

And this works on Android and iOS.

**Comment by maj0rr** [comment]
Any update on this?
Got same issue. 

$vcard->download();
Return person.vcf.json in safari 
and person.vcf in chrome

Which header do I have to set to get this work properly?

**Comment by daviddelusenet** [comment]
@maj0rr I'm using the Symfony framework and manged to get it working with the `Symfony\Component\HttpFoundation\Response` class. This is what I did:

```
// 4a. setup response
$response = new Response();

// 4b. add response content and status code
$response->setContent($vcard);
$response->setStatusCode(Response::HTTP_OK);

// 4c. add response headers
$response->headers->set('Content-Type', 'text/x-vcard');
$response->headers->set('Content-Disposition', 'attachment; filename="'.$filename.'"');
$response->headers->set('Content-Length', mb_strlen($vcard, 'utf-8'));

// 5. return the vcard
return $response;
```

The `$vCard` variable just contains the vCard returned as string (snippet from another file: `return $vcard->getOutput();`).

This worked for me. Good luck!

**Comment by maj0rr** [comment]
Thanks @daviddelusenet,
that works for me also!

`
use Symfony\Component\HttpFoundation\Response;

$content = $vcard->getOutput();

$response = new Response();
$response->setContent($content);
$response->setStatusCode(200);
$response->headers->set('Content-Type', 'text/x-vcard');
$response->headers->set('Content-Disposition', 'attachment; filename="'.str_slug($name).'.vcf"');
$response->headers->set('Content-Length', mb_strlen($content, 'utf-8'));
`

**Comment by jeroendesloovere** [comment]
Good job guys!

**Comment by zloadmin** [comment]
I had some problem with string 
`$response->headers->set('Content-Length', mb_strlen($content, 'utf-8'));`
due to i had Spain name. And this code wrong count length. (On iPhone). So i've just deleted this string.

**Comment by anoozz** [comment]
mine isnt working .. with return $response; download pending..

**Comment by umefarooq** [comment]
with Laravel save the vcard in a directory. Download it with response file.

$vcard->setSavePath('/path/to/directory');
$vcard->save();

download with response 
return response()->file($pathToFile);

vcard save file name in lower letters, on linux you will get file not found error. first lower case the file with strtolower than pass it to response file.

**Comment by aadilbashirbhat** [comment]
> $content = $vcard->getOutput();
> 
> $response = new Response();
> $response->setContent($content);
> $response->setStatusCode(200);
> $response->headers->set('Content-Type', 'text/x-vcard');
> $response->headers->set('Content-Disposition', 'attachment; filename="'.str_slug($name).'.vcf"');
> $response->headers->set('Content-Length', mb_strlen($content, 'utf-8'));
> 
> return $response;

Thanks, it really helps me out
