### ISSUE TITLE
addPhotoEncoded() disappeared

### ISSUE THREAD

**Issue by aelores** [jeroendesloovere/vcard#92]
Hi,

First I want to thank you for your work. This is great.

Since the last upgrade I cannot use the base64 string image format. It seems that "addPhotoEncoded" has disappeared.
IS there a replacement mechanism for this situation ?...

Best regards...

**Comment by Stadly** [comment]
The possibility to add the image content directly instead of relying on an url would indeed be nice.

**Comment by Stadly** [comment]
I've created a pull request for this here: https://github.com/jeroendesloovere/vcard/pull/103

**Comment by jeroendesloovere** [comment]
Hi y'all, thanks for the message.
I've merged the PR from @Stadly, so I'm closing this one.
