### ISSUE TITLE
addPhoto error

### ISSUE THREAD

**Issue by fmcdigital** [jeroendesloovere/vcard#94]
I'm having the following issue:
```
mime_content_type(): Failed identify data 0:(null)
```

When trying to use the default image:
```
$vcard->addPhoto('https://raw.githubusercontent.com/jeroendesloovere/vcard/master/tests/image.jpg');
```

**Comment by Synchro** [comment]
I've run into this too, and I've tracked down the problem. The `addMedia` method calls `mime_content_type`, which does not work with URLs, only local paths. This is just a bug, needs fixing. The thing which is annoying is that the code to extract the MIME type from response headers is already there in the part that's used if you set `include = false` - it just needs checking before it gets to there.
