### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by to-be-the-best** [jeroendesloovere/vcard#98]
I noticed that in the composer file a PHP version of 5.3.3 is still accepted, while the code actually uses version 5.4 and above, meaning the code is no longer running at 5.3.3.
Personally, I would like to follow the example of Symfony 3 and increase the php version in the composer file to 5.5.9.
I am very curious about your opinion.

**Comment by to-be-the-best** [comment]
If you want, I can make a pull request with my proposal.
This would be with php version 5.5.9.

**Comment by to-be-the-best** [comment]
@jeroendesloovere If you do not want this, please say it, I'll do it on my own fork the way I think it should.

**Comment by jeroendesloovere** [comment]
Hi @to-be-the-best a PR is always welcome.

**Comment by jeroendesloovere** [comment]
Closing this one
